### Create a new Circle
POST http://localhost:3500/circle/create HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRJZCI6ImE5ZDA5NDIyLTkwMTItMTFlYS05NjU3LTAwMjU5MDdlZDYzMCIsImlhdCI6MTU4ODg3MTE3NywiZXhwIjoxNTg4ODc0Nzc3fQ.PeOmAN6ulN3SOu4RgLrgx7F8K6njjZMqrYgz5bjA7QU
content-type: application/json

{
    "name": "Soccer team"
}
