### Simulate Create a new User - JSON 
POST http://localhost:3500/user/create HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@gmail.com",
    "password": "Test123456",
    "firstName": "Eduardo",
    "lastName": "Pereira do Carmo"
}

### Simulate Login
POST http://localhost:3500/user/auth HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@gmail.com",
    "password": "Test123456"
}

### Resend a Validation Email
POST http://localhost:3500/user/resendValidationEmail HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@outlook.com"
}

### Forgot Password
POST http://localhost:3500/user/forgotPassword HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@outlook.com"
}

### Change Use Password
POST http://localhost:3500/user/chagePassword HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRJZCI6ImJmYmVhMjJiLThiZGEtMTFlYS05NjU3LTAwMjU5MDdlZDYzMCIsImlhdCI6MTU4ODYzODk2MSwiZXhwIjoxNTg4NjQyNTYxfQ.ixXLdlEhyCvtz5D3cK5AU1OGEFlKIl78UnK2DeP19gg

{
    "password": "Test12345678"
}
