### Simulate Create a new User - JSON 
POST http://localhost:3500/user/create HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@outlook.com",
    "password": "Test123456",
    "firstName": "Eduardo",
    "lastName": "Pereira do Carmo"
}

### Simulate Create a new User - JSON Erro
POST http://localhost:3500/user/create HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@outlook.com",
    "password": "",
    "firstName": "Eduardo",
    "lastName": "Pereira do Carmo"
}

### Simulate Create a new User - urlencoded 
POST http://localhost:3500/user/create HTTP/1.1
Content-Type: application/x-www-form-urlencoded

email=ecarmo@outlook.com
&password=Test123456
&firstName=Eduardo
&lastName=Pereira do Carmo


### Simulate Check an user email

GET http://localhost:3500/user/checkEmail?token=522effe398fb7336a367e353f1f098e483f05fa67fa5538b19fbc02e6d9b21026332f6f7abff944b1d2731c2010af416ca4c76be1f35962826547fd3294a7159af812ae0219b014998feba5eb7d2d2a213b450b4bb4941f655771a3aa3059f2dd8997504ff2ed07294f248bd77459a3518dd0251137a4eecbe1fd843eec5e45
content-type: application/json

### Simulate Login
POST http://localhost:3500/user/auth HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@outlook.com",
    "password": "Test123456"
}

### Simulate Login - Erro Validation
POST http://localhost:3500/user/auth HTTP/1.1
content-type: application/json

{
    "email": "ecarmo2@gmail.com",
    "password": "Test123456"
}

### Resend a Validation Email
POST http://localhost:3500/user/resendValidationEmail HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@outlook.com"
}

### Forgot Password
POST http://localhost:3500/user/forgotPassword HTTP/1.1
content-type: application/json

{
    "email": "ecarmo@outlook.com"
}

### Change Use Password
POST http://localhost:3500/user/chagePassword HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHRJZCI6ImJmYmVhMjJiLThiZGEtMTFlYS05NjU3LTAwMjU5MDdlZDYzMCIsImlhdCI6MTU4ODYzODk2MSwiZXhwIjoxNTg4NjQyNTYxfQ.ixXLdlEhyCvtz5D3cK5AU1OGEFlKIl78UnK2DeP19gg

{
    "password": "Test12345678"
}
